# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-DotNetXML
version:      1.5
version_from: lib/Config/DotNetXML.pm
installdirs:  site
requires:
    Test::More:                    0.33
    XML::XPath:                    1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
