---
abstract: 'Use .Net XML COnfig files.'
author:
  - 'Jonathan Stowe (jns@gellyfish.co.uk)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-DotNetXML
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0.33'
  XML::XPath: '1.13'
resources:
  repository: https://github.com/jonathanstowe/Config-DotNetXML.git
version: '1.5'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
