#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-DotNetXML
version:      undef
version_from: lib/Config/DotNetXML.pm
installdirs:  site
requires:
    Test::More:                    0.33
    XML::Parser:                   2.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
